Periodic check-in

diff --git a/bash/bash_func b/bash/bash_func
--- a/bash/bash_func
+++ b/bash/bash_func
@@ -27,7 +27,7 @@ unset -f du1
 function du1() { duf $1 1; }
 
 
-# DIRSTACK                                                                                         {{{1
+# DIRSTACK                                                                                                          {{{1
 # chdir is aliased to cd so that cd's update the stack and create a new prompt.  DO NOT alias -k cd!!!
 # A 'history' of cd's is remembered.
 # 'cd ='  lists the contents of the stack.
@@ -98,12 +98,12 @@ function du1() { duf $1 1; }
 #alias cd=dirstack
 
 
-# Silent push and popd. Use dirs -v for vertical dirstack                                          {{{1
+# Silent push and popd. Use dirs -v for vertical dirstack                                                           {{{1
 function pushd { command pushd $@ > /dev/null ; }
 function popd  { command popd  $@ > /dev/null ; }
 
 
-# Emulate Zsh's behavior of pushd lifting the directory to tos instead of cycling the stack        {{{1
+# Emulate Zsh's behavior of pushd lifting the directory to tos instead of cycling the stack                         {{{1
 function zsh_cd {
   if (( $#==0 )); then
     if [[ $REPO_PATH == "" ]]; then
@@ -162,7 +162,7 @@ function zsh_cd {
 alias cd=zsh_cd
 
 
-# Function to convert tr0 to pun                                                                   {{{1
+# Function to convert tr0 to pun                                                                                    {{{1
 #function tr2pun(){
 #    for i in $*; do
 #        echo
@@ -174,7 +174,7 @@ alias cd=zsh_cd
 #}
 
 
-# Function to convert latex file to pdf                                                            {{{1
+# Function to convert latex file to pdf                                                                             {{{1
 #function tex2pdf(){
 #    for i in $*; do
 #        file=`basename $i .tex`
@@ -188,7 +188,7 @@ alias cd=zsh_cd
 #}
 
 
-# Function to print column no. n of space-separated input                                          {{{1
+# Function to print column no. n of space-separated input                                                           {{{1
 # SYNTAX:
 #   echo " 1  2  3" | col 1
 #     should print 2
@@ -201,7 +201,7 @@ function colm {
 }
 
 
-# Function to submit tr0 to pun conversion to short queue in lsf                                   {{{1
+# Function to submit tr0 to pun conversion to short queue in lsf                                                    {{{1
 #function lsftr2pun(){
 #    for i in $*; do
 #        /usr/local/lsf/bin/bsub -P P0:IO_10015123 -q short -o /dev/null -R ws40 -J tr2pun converter -t punch -i `basename $i 0` -o `basename $i .tr0`
@@ -210,11 +210,11 @@ function colm {
 #}
 
 
-# Function to create new dir(s) and enter it (last directory if multiple arguments are given)      {{{1
+# Function to create new dir(s) and enter it (last directory if multiple arguments are given)                       {{{1
 function mcd(){ mkdir -p $1 && cd $1; }
 
 
-# Function to compile and simulate verilog using Icarus Verilog                                    {{{1
+# Function to compile and simulate verilog using Icarus Verilog                                                     {{{1
 #function vsim(){
 #  out=`basename $*[1] .v`.out
 #    iverilog -o $out $*
@@ -225,7 +225,7 @@ function mcd(){ mkdir -p $1 && cd $1; }
 #}
 
 
-# Function to compile c source files and generate output files of the same name                    {{{1
+# Function to compile c source files and generate output files of the same name                                     {{{1
 #function gcp(){
 #    for i in $*; do
 #        out=`basename $i .c`
@@ -238,7 +238,7 @@ function mcd(){ mkdir -p $1 && cd $1; }
 #}
 
 
-# Function to kill all jobs that match a pattern                                                   {{{1
+# Function to kill all jobs that match a pattern                                                                    {{{1
 #function bkillall(){
 #    for i in `bjg $1 | cut -d" " -f1`; do
 #        bkill $i
@@ -248,7 +248,7 @@ function mcd(){ mkdir -p $1 && cd $1; }
 #}
 
 
-# Function to move multiple files to directory which is specified as the last argument             {{{1
+# Function to move multiple files to directory which is specified as the last argument                              {{{1
 # Same functionality can be achieved by
 #   mv {file1, file2 ...} dest_dir
 # Curly braces may be omitted in BASH
@@ -266,7 +266,7 @@ function mcd(){ mkdir -p $1 && cd $1; }
 #}
 
 
-# Function to find and print all Sub-spice tags in the deck                                        {{{1
+# Function to find and print all Sub-spice tags in the deck                                                         {{{1
 #function findtags(){
 #  for i in $*; do
 #    print "$i : "
@@ -277,7 +277,7 @@ function mcd(){ mkdir -p $1 && cd $1; }
 #}
 
 
-# Function to convert HSPICE mt* files to TISPICE prt format                                       {{{1
+# Function to convert HSPICE mt* files to TISPICE prt format                                                        {{{1
 #function mt2prt(){
 #  for i in $*; do
 #    print "Converting $i..."
@@ -288,7 +288,7 @@ function mcd(){ mkdir -p $1 && cd $1; }
 #}
 
 
-# Function to summarise the number of jobs running in LSF queue                                    {{{1
+# Function to summarise the number of jobs running in LSF queue                                                     {{{1
 #function cjobs(){
 #  /usr/local/lsf/bin/bjobs >| /tmp/$$
 #  lsfjobs[running]=`grep -c RUN /tmp/$$`
@@ -298,7 +298,7 @@ function mcd(){ mkdir -p $1 && cd $1; }
 #  return
 #}
 
-# Handling temporary file backups                                                                  {{{1
+# Handling temporary file backups                                                                                   {{{1
 function bak(){
   for i in $*; do
     cp $i{,.bak}
@@ -319,13 +319,13 @@ function unbak(){
 }
 
 
-# Function to untar, and unzip an archive                                                          {{{1
+# Function to untar, and unzip an archive                                                                           {{{1
 #function targz(){
 #    gunzip -c $1 | tar xvf -
 #}
 
 
-# For csh compatibility                                                                            {{{1
+# For csh compatibility                                                                                             {{{1
 function setenv(){
   var=$1
   shift
@@ -335,7 +335,7 @@ function setenv(){
 }
 
 
-# Misc                                                                                             {{{1
+# Misc                                                                                                              {{{1
 #function hspx(){
 #    for i in $*; do
 #        cell=`basename $i .hsp`
@@ -401,7 +401,7 @@ uc(){ echo $* |/usr/bin/tr "[a-z]" "[A-Z]"; }
 
 
 unset -f get_vcs_type
-function get_vcs_type {                                                                          # {{{1
+function get_vcs_type {                                                                                           # {{{1
   # Description: Check if specified directory is under a Version-controlled system
   # Arguments: 1 - Variable to return VCS type
   #            2 - Directory to check. If skipped, defaults to PWD
@@ -429,7 +429,7 @@ function get_vcs_type {                                                         
 
 
 unset -f get_vcs_branch
-function get_vcs_branch {                                                                        # {{{1
+function get_vcs_branch {                                                                                         # {{{1
   # Description: If PWD is under a VCS, return the branch. If not, return an empty string
   # Arguments: 1 - The variable into which the branch name must be written
 
@@ -451,7 +451,7 @@ function get_vcs_branch {                                                       
   fi
 }
 
-# Coloured man pages with less                                                                     {{{1
+# Coloured man pages with less                                                                                      {{{1
 function man() {
   env \
     LESS_TERMCAP_mb=$(printf "\e[1;31m") \
@@ -463,3 +463,58 @@ function man() {
     LESS_TERMCAP_us=$(printf "\e[1;32m") \
       man "$@"
 }
+
+
+# Automatically add completion for all aliases to commands having completion functions                              {{{1
+# Keep this at the end
+function alias_completion {
+  local namespace="alias_completion"
+
+  # parse function based completion definitions, where capture group 2 => function and 3 => trigger
+  local compl_regex='complete( +[^ ]+)* -F ([^ ]+) ("[^"]+"|[^ ]+)'
+  # parse alias definitions, where capture group 1 => trigger, 2 => command, 3 => command arguments
+  local alias_regex="alias ([^=]+)='(\"[^\"]+\"|[^ ]+)(( +[^ ]+)*)'"
+
+  # create array of function completion triggers, keeping multi-word triggers together
+  eval "local completions=($(complete -p | sed -ne "/$compl_regex/s//'\3'/p"))"
+  (( ${#completions[@]} == 0 )) && return 0
+
+  # create temporary file for wrapper functions and completions
+  rm -f "/tmp/${namespace}-*.tmp" # preliminary cleanup
+  local tmp_file="$(mktemp "/tmp/${namespace}-${RANDOM}.tmp")" || return 1
+
+  # read in "<alias> '<aliased command>' '<command args>'" lines from defined aliases
+  local line; while read line; do
+    eval "local alias_tokens=($line)" 2>/dev/null || continue # some alias arg patterns cause an eval parse error
+    local alias_name="${alias_tokens[0]}" alias_cmd="${alias_tokens[1]}" alias_args="${alias_tokens[2]# }"
+
+    # skip aliases to pipes, boolan control structures and other command lists
+    # (leveraging that eval errs out if $alias_args contains unquoted shell metacharacters)
+    eval "local alias_arg_words=($alias_args)" 2>/dev/null || continue
+
+    # skip alias if there is no completion function triggered by the aliased command
+    [[ " ${completions[*]} " =~ " $alias_cmd " ]] || continue
+    local new_completion="$(complete -p "$alias_cmd")"
+
+    # create a wrapper inserting the alias arguments if any
+    if [[ -n $alias_args ]]; then
+        local compl_func="${new_completion/#* -F /}"; compl_func="${compl_func%% *}"
+        # avoid recursive call loops by ignoring our own functions
+        if [[ "${compl_func#_$namespace::}" == $compl_func ]]; then
+            local compl_wrapper="_${namespace}::${alias_name}"
+                echo "function $compl_wrapper {
+                    (( COMP_CWORD += ${#alias_arg_words[@]} ))
+                    COMP_WORDS=($alias_cmd $alias_args \${COMP_WORDS[@]:1})
+                    $compl_func
+                }" >> "$tmp_file"
+                new_completion="${new_completion/ -F $compl_func / -F $compl_wrapper }"
+        fi
+    fi
+
+    # replace completion trigger by alias
+    new_completion="${new_completion% *} $alias_name"
+    echo "$new_completion" >> "$tmp_file"
+  done < <(alias -p | sed -ne "s/$alias_regex/\1 '\2' '\3'/p")
+  source "$tmp_file" && rm -f "$tmp_file"
+};
+alias_completion
